name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      # - name: Upload build artifacts
      #   if: success()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     path: build/  # Adjust the path to your build output directory if different

      # - name: Add SSH key
      #   uses: webfactory/ssh-agent@v0.8.1
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Upload to remote server
      #   run: scp -r build/ user@yourserver:/path/to/destination
      #   env:
      #     SSH_KNOWN_HOSTS: ${{ secrets.SSH_HOST }}
